export const KAFKA_CLIENT_HEADERS_REQUEST_BUILDER_DI = Symbol('KAFKA_CLIENT_HEADERS_REQUEST_BUILDER_DI');
export const KAFKA_CLIENT_PRODUCER_REQUEST_SERIALIZER_DI = Symbol('KAFKA_CLIENT_PRODUCER_REQUEST_SERIALIZER_DI');
export const KAFKA_CLIENT_PROXY_BUILDER_OPTIONS_DI = Symbol('KAFKA_CLIENT_PROXY_BUILDER_OPTIONS_DI');
export const KAFKA_CLIENT_PROXY_DI = Symbol('KAFKA_CLIENT_PROXY_DI');
