version: '3'

volumes:
  postgres:
    external: true
  redis:
    external: true

services: 
  redis: 
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    command: redis-server --appendonly yes

  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
      TZ: "Europe/Moskow"
    ports:
        - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
