services: 
  demo-hybrid-microservice:
    build:
      context: ../
    container_name: 'demo-hybrid-microservice'
    restart: always
    volumes:
      - ../:/app
      - /app/node_modules
      - /app/protos/compiled
    entrypoint: ["sh", "-c", "[ -f /app/.env ] || cp /app/.example.env /app/.env; exec npm --prefix=/app run start:dev"]
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - dev-local
