export const GRPC_CLIENT_REQUEST_OPTIONS_DI = Symbol('GRPC_CLIENT_REQUEST_OPTIONS_DI');
export const GRPC_CLIENT_PROXY_BUILDER_OPTIONS_DI = Symbol('GRPC_CLIENT_PROXY_BUILDER_OPTIONS_DI');
export const GRPC_CLIENT_PROXY_DI = Symbol('GRPC_CLIENT_PROXY_DI');
export const GRPC_CLIENT_METADATA_REQUEST_BUILDER_DI = Symbol('GRPC_CLIENT_METADATA_REQUEST_BUILDER_DI');
