export const RABBIT_MQ_CLIENT_PUBLISH_OPTIONS_BUILDER_DI = Symbol('RABBIT_MQ_CLIENT_PUBLISH_OPTIONS_BUILDER_DI');
export const RABBIT_MQ_CLIENT_PRODUCER_REQUEST_SERIALIZER_DI = Symbol(
  'RABBIT_MQ_CLIENT_PRODUCER_REQUEST_SERIALIZER_DI',
);
export const RABBIT_MQ_CLIENT_PROXY_OPTIONS_DI = Symbol('RABBIT_MQ_CLIENT_PROXY_OPTIONS_DI');
export const RABBIT_MQ_CLIENT_PROXY_DI = Symbol('RABBIT_MQ_CLIENT_PROXY_DI');
